import type { Peak } from '@/lib/types';

type PeakSeed = Omit<Peak, 'id' | 'created_at' | 'description'> & {
  description?: string | null;
};

export const PEAKS_SEED: PeakSeed[] = [
  {
    slug: 'hallasan',
    name_ko: '한라산',
    name_en: 'Hallasan',
    elevation_m: 1947,
    latitude: 33.3617,
    longitude: 126.5292,
    region: '제주특별자치도',
    region_short: '제주',
    difficulty: '중',
    list_korea_100: true,
    list_baekdudaegan: false,
    description: null,
  },
  {
    slug: 'jirisan',
    name_ko: '지리산',
    name_en: 'Jirisan',
    elevation_m: 1915,
    latitude: 35.3372,
    longitude: 127.7307,
    region: '전라남도',
    region_short: '전남',
    difficulty: '상',
    list_korea_100: true,
    list_baekdudaegan: true,
    description: null,
  },
  {
    slug: 'seoraksan',
    name_ko: '설악산',
    name_en: 'Seoraksan',
    elevation_m: 1708,
    latitude: 38.1196,
    longitude: 128.4655,
    region: '강원특별자치도',
    region_short: '강원',
    difficulty: '상',
    list_korea_100: true,
    list_baekdudaegan: true,
    description: null,
  },
  {
    slug: 'deokyusan',
    name_ko: '덕유산',
    name_en: 'Deokyusan',
    elevation_m: 1614,
    latitude: 35.8602,
    longitude: 127.7466,
    region: '전북특별자치도',
    region_short: '전북',
    difficulty: '중',
    list_korea_100: true,
    list_baekdudaegan: true,
    description: null,
  },
  {
    slug: 'taebaeksan',
    name_ko: '태백산',
    name_en: 'Taebaeksan',
    elevation_m: 1567,
    latitude: 37.0998,
    longitude: 128.9165,
    region: '강원특별자치도',
    region_short: '강원',
    difficulty: '중',
    list_korea_100: true,
    list_baekdudaegan: true,
    description: null,
  },
  {
    slug: 'odaesan',
    name_ko: '오대산',
    name_en: 'Odaesan',
    elevation_m: 1563,
    latitude: 37.796,
    longitude: 128.543,
    region: '강원특별자치도',
    region_short: '강원',
    difficulty: '중',
    list_korea_100: true,
    list_baekdudaegan: true,
    description: null,
  },
  {
    slug: 'gayasan',
    name_ko: '가야산',
    name_en: 'Gayasan',
    elevation_m: 1430,
    latitude: 35.8204,
    longitude: 128.1206,
    region: '경상남도',
    region_short: '경남',
    difficulty: '중',
    list_korea_100: true,
    list_baekdudaegan: false,
    description: null,
  },
  {
    slug: 'sobaeksan',
    name_ko: '소백산',
    name_en: 'Sobaeksan',
    elevation_m: 1439,
    latitude: 36.9583,
    longitude: 128.4905,
    region: '충청북도',
    region_short: '충북',
    difficulty: '중',
    list_korea_100: true,
    list_baekdudaegan: true,
    description: null,
  },
  {
    slug: 'woraksan',
    name_ko: '월악산',
    name_en: 'Woraksan',
    elevation_m: 1094,
    latitude: 36.8855,
    longitude: 128.1064,
    region: '충청북도',
    region_short: '충북',
    difficulty: '상',
    list_korea_100: true,
    list_baekdudaegan: false,
    description: null,
  },
  {
    slug: 'bukhansan',
    name_ko: '북한산',
    name_en: 'Bukhansan',
    elevation_m: 837,
    latitude: 37.6584,
    longitude: 126.9778,
    region: '서울특별시',
    region_short: '서울',
    difficulty: '중',
    list_korea_100: true,
    list_baekdudaegan: false,
    description: null,
  },
  {
    slug: 'gwanaksan',
    name_ko: '관악산',
    name_en: 'Gwanaksan',
    elevation_m: 632,
    latitude: 37.4423,
    longitude: 126.9628,
    region: '서울특별시',
    region_short: '서울',
    difficulty: '하',
    list_korea_100: true,
    list_baekdudaegan: false,
    description: null,
  },
  {
    slug: 'dobongsan',
    name_ko: '도봉산',
    name_en: 'Dobongsan',
    elevation_m: 740,
    latitude: 37.6906,
    longitude: 127.014,
    region: '서울특별시',
    region_short: '서울',
    difficulty: '중',
    list_korea_100: true,
    list_baekdudaegan: false,
    description: null,
  },
];

export const TOTAL_TARGET = 100;
